# Use nightly instead
#addons:
#  firefox: "33.1"

# Let's get a virtual display so that we can run Firefox
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"
  - npm install mozilla-download -g
  - cd ..
  - mozilla-download --branch mozilla-central -c prerelease firefox
  - cd $TRAVIS_BUILD_DIR

notifications:
  irc:
    channels:
      - "irc.mozilla.org#perf"
    template:
     - "BenWa: %{repository} (%{commit}) : %{message} %{build_url}"
    on_success: change
    on_failure: change

script: ./test.sh $TRAVIS_BUILD_DIR/../firefox/firefox
#script: ./test.sh
